---
- name: Installation de nginx
  apk: name=nginx update_cache=yes

- name: Désactivation du server par défaut (vérification de l'existence d'un fichier de conf par défaut)
  stat: path={{nginx_config_dir}}/default.conf
  register: stat_result

- name: Désactivation du server par défaut (copie d'une sauvegarde)
  copy: remote_src=true src={{nginx_config_dir}}/default.conf dest={{nginx_config_dir}}/default.conf.inactive
  when: stat_result.stat.exists

- name: Désactivation du server par défaut (suppression de la conf par defaut)
  file: path={{nginx_config_dir}}/default.conf state=absent

- name: Démarrage de nginx
  service: name=nginx state=started
